[CETE-1234] test: install husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,9 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/sh
+if ! head -1 "$1" | grep -qE "(\[CETE-[0-9]{1,10}\])( )(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?:.{1,}$"; then
+    echo "Aborting commit. Your commit message is invalid. Format: [CETE-0000] feat: description" >&2
+    exit 1
+fi
+if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
+    echo "Aborting commit. Your commit message is too long than 88 character." >&2
+    exit 1
+fi
